# Automatically format clojure code using cljstyle
# For more information, please visit: https://github.com/Wall-Brew-Co/open-source/blob/master/README.md#automating-opinions
name: Formatter

on: [pull_request]

jobs:
  formatting:
    # This job requires the Wall Brew Bot Token, so it is only run on non-forked repositories
    if: github.repository_owner == 'Wall-Brew-Co'

    runs-on: ubuntu-latest

    steps:
      - name: Echo Trigger
        id: echo-trigger
        run: echo "Job triggered by ${{ github.event_name }}"

      - name: Echo Runner OS
        id: echo-runner-os
        run: echo "Job running on ${{ runner.os }} server"

      - name: Echo Git Ref
        id: echo-git-ref
        run: echo "Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      # Checkout the repository with our Wall Brew Bot Token
      # We need this so any changes can be committed back to the repository
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WALL_BREW_BOT_PAT }}

      - name: Setup Java
        id: install-java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'adopt'
          java-version: '21'
          # This should match system.properties

      - name: Install Leiningen
        id: install-leiningen
        uses: DeLaGuardo/setup-clojure@13.5
        with:
          lein: 'latest'
          clj-kondo: 'latest'
          cljstyle: 'latest'

      - name: Format Clojure Code
        id: format
        run: |
          cljstyle fix --report --report-timing --verbose

      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: |
            [Format] Auto-formatting

      - name: Echo Status
        id: echo-status
        run: echo "Job status is ${{ job.status }}."

# This file was automatically copied and populated by rebroadcast
# Do not edit this file directly, instead modify the source at https://github.com/Wall-Brew-Co/rebroadcast/blob/master/sources/github-actions/workflows/format.yml
