# Greet new contributors on their first interaction with the repository
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    # This job requires the Wall Brew Bot Token, so it is only run on non-forked repositories
    if: github.repository_owner == 'Wall-Brew-Co'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Trigger
        id: echo-trigger
        run: echo "Job triggered by ${{ github.event_name }}"

      - name: Echo Runner OS
        id: echo-runner-os
        run: echo "Job running on ${{ runner.os }} server"

      - name: Echo Git Ref
        id: echo-git-ref
        run: echo "Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Greet New Contributors
        id: greet
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.WALL_BREW_BOT_PAT }}
          issue-message: 'Thank you for taking the time to let us know!'
          pr-message: 'Congratulations! This is your first contribution!'

      - name: Echo Status
        id: echo-status
        run: echo "Job status is ${{ job.status }}."

# This file was automatically copied and populated by rebroadcast
# Do not edit this file directly, instead modify the source at https://github.com/Wall-Brew-Co/rebroadcast/blob/master/sources/github-actions/workflows/greetings.yml
