# Apply GitHub Labels to Pull Requests
name: Label Pull Requests

on: [pull_request]

jobs:
  label:
    # This job requires the Wall Brew Bot Token, so it is only run on non-forked repositories
    if: github.repository_owner == 'Wall-Brew-Co'

    runs-on: ubuntu-latest

    steps:
      - name: Echo Trigger
        id: echo-trigger
        run: echo "Job triggered by ${{ github.event_name }}"

      - name: Echo Runner OS
        id: echo-runner-os
        run: echo "Job running on ${{ runner.os }} server"

      - name: Echo Git Ref
        id: echo-git-ref
        run: echo "Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Label Pull Requests
        id: label
        uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.WALL_BREW_BOT_PAT }}"

      - name: Echo Status
        id: echo-status
        run: echo "Job status is ${{ job.status }}."

# This file was automatically copied and populated by rebroadcast
# Do not edit this file directly, instead modify the source at https://github.com/Wall-Brew-Co/rebroadcast/blob/master/sources/github-actions/workflows/label.yml
