name: Linter
on: [pull_request, workflow_dispatch]

jobs:
  spell-check:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  clj-kondo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Clojure
        uses: nnichols/clojure-lint-action@v1
        with:
          github_token: ${{ secrets.WALL_BREW_BOT_PAT }}
          reporter: github-pr-review
          filter_mode: file
